[build-system] #will use setuptools library for building this package
requires = ["setuptools>=60.0", "wheel"]
build-backends = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true