#### --- file configuration ---
[build-system]
requires = ["setuptools>=60.0","wheel"]
build-backends = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.mypy]
mupy_path = "src"
ignore_missing_imports = true